Add: created pull request template
kachun333/OurPromise pull request #56
Opened 2022-12-28 00:55 UTC by Niravprajapati1

Created pull request template 
issue number #52

2022-12-28 02:01 UTC, kachun333 commented
@Niravprajapati1 , you forget to use one of the keywords

![image](https://user-images.githubusercontent.com/34387770/209745573-a6ac142f-ceb9-4e63-9c77-26ab1c086293.png)

Please have a look: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2022-12-30 07:02 UTC, Niravprajapati1 commented
You can review now

2023-01-01 06:45 UTC, kachun333 requested changes
hi @Niravprajapati1 , I proposed to keep the PR template simple

2023-01-01 06:45 UTC, kachun333 commented on .github/pull_request_template.md
> +- [ ] The title of my pull request is a short description of the requested changes.
Not needed for this project 

```suggestion
```

2023-01-01 06:45 UTC, kachun333 commented on .github/pull_request_template.md
> +<!-- Add notes to reviewers if applicable -->
```suggestion
## Additional Notes

-
```

2023-01-01 06:45 UTC, kachun333 commented on .github/pull_request_template.md
> +<!-- Add all the screenshots which support your changes -->
```suggestion
## Screenshots

-
```

2023-01-01 06:45 UTC, kachun333 commented on .github/pull_request_template.md
> +-->
```suggestion
## Describe Your Changes

-
```

2023-01-01 06:45 UTC, kachun333 commented on .github/pull_request_template.md
> +<!-- Example: Closes #31 -->
```suggestion
## Fixed Issue(s)

- 
```

2023-01-01 06:45 UTC, kachun333 commented on .github/pull_request_template.md
> +<!-- If your PR fixes an open issue, use `Closes #999` to link your PR with the issue. #999 stands for the issue number you are fixing -->
```suggestion
```

2023-01-01 11:46 UTC, kachun333 approved these changes

2023-01-01 11:48 UTC, merged

2023-01-01 11:48 UTC, kachun333 commented
thanks @Niravprajapati1

2023-01-01 15:58 UTC, Niravprajapati1 commented
No problem 👍